/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JuliaRouteImport } from './routes/julia'
import { Route as IndexRouteImport } from './routes/index'

const JuliaRoute = JuliaRouteImport.update({
  id: '/julia',
  path: '/julia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/julia': typeof JuliaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/julia': typeof JuliaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/julia': typeof JuliaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/julia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/julia'
  id: '__root__' | '/' | '/julia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JuliaRoute: typeof JuliaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/julia': {
      id: '/julia'
      path: '/julia'
      fullPath: '/julia'
      preLoaderRoute: typeof JuliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JuliaRoute: JuliaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
